services:
  rsm-msba:
    image: vnijs/rsm-msba-k8s-intel:latest
    container_name: rsm-msba-k8s-intel
    environment:
      TZ: America/Los_Angeles
      USER: jovyan
      HOME: /home/jovyan
      SHELL: /bin/zsh
      PYTHONUSERBASE: /home/jovyan/.rsm-msba
      JUPYTER_PATH: /home/jovyan/.rsm-msba/share/jupyter
      JUPYTER_RUNTIME_DIR: /tmp/jupyter/runtime
      JUPYTER_CONFIG_DIR: /home/jovyan/.rsm-msba/jupyter
    volumes:
      - ${HOME}:/home/jovyan
      - pg_data:/var/lib/postgresql/16/main
    networks:
      - rsm-docker

networks:
  rsm-docker:
    name: rsm-docker

volumes:
  pg_data:
    name: pg_data