# kubernetes-ssh-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsm-msba-${USER}  # Will be replaced with host username
  labels:
    app: rsm-msba
    user: ${USER}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsm-msba
      user: ${USER}
  template:
    metadata:
      annotations:
        NB_UID: "${USER_UID}"  # Will be replaced with host UID
        NB_GID: "${USER_GID}"  # Will be replaced with host GID
      labels:
        app: rsm-msba
        user: ${USER}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: ${USER_GID}
      containers:
      - name: rsm-msba-container
        image: vnijs/rsm-msba-k8s-intel:latest
        resources:
          requests:
            memory: "16Gi"
            cpu: "2"
          limits:
            memory: "32Gi"
            cpu: "4"
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: USER
          value: "jovyan"
        - name: HOME
          value: "/home/jovyan"
        - name: SHELL
          value: "/bin/zsh"
        - name: ZDOTDIR
          value: /home/jovyan/.rsm-msba/zsh
        - name: PYTHONUSERBASE
          value: "/home/jovyan/.rsm-msba"
        - name: JUPYTER_PATH
          value: "/home/jovyan/.rsm-msba/share/jupyter"
        - name: JUPYTER_RUNTIME_DIR
          value: "/tmp/jupyter/runtime"
        - name: JUPYTER_CONFIG_DIR
          value: "/home/jovyan/.rsm-msba/jupyter"
        - name: NB_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['NB_UID']
        - name: NB_GID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['NB_GID']
        ports:
        - containerPort: 22
        # - containerPort: 8765
        # - containerPort: 8181
        # - containerPort: 8282
        # - containerPort: 8000
        volumeMounts:
        - name: home-volume
          mountPath: /home/jovyan
      volumes:
      - name: home-volume
        hostPath:
          path: /home/${USER}  # Will be replaced with actual home directory
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: rsm-msba-ssh-${USER}  # Will be replaced with actual username
spec:
  type: NodePort
  selector:
    app: rsm-msba
    user: ${USER}
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: postgresql
    protocol: TCP
    port: 8765
    targetPort: 8765
