apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsm-msba-gpu-${USER}
  labels:
    app: rsm-msba-gpu
    user: ${USER}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsm-msba-gpu
      user: ${USER}
  template:
    metadata:
      annotations:
        NB_UID: "${USER_UID}"
        NB_GID: "${USER_GID}"
      labels:
        app: rsm-msba-gpu
        user: ${USER}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: ${USER_GID}
      containers:
      - name: rsm-msba-container
        image: vnijs/rsm-msba-k8s-gpu:${GPU_VERSION}
        resources:
          requests:
            memory: "32Gi"
            cpu: "1"
            nvidia.com/gpu: 1  # Request 1 GPU
          limits:
            memory: "64Gi"
            cpu: "2"
            nvidia.com/gpu: 1  # Limit to 1 GPU
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: USER
          value: "jovyan"
        - name: HOME
          value: "/home/jovyan"
        - name: SHELL
          value: "/bin/zsh"
        - name: ZDOTDIR
          value: /home/jovyan/.rsm-msba/zsh
        - name: PYTHONUSERBASE
          value: "/home/jovyan/.rsm-msba"
        - name: JUPYTER_PATH
          value: "/home/jovyan/.rsm-msba/share/jupyter"
        - name: JUPYTER_RUNTIME_DIR
          value: "/tmp/jupyter/runtime"
        - name: JUPYTER_CONFIG_DIR
          value: "/home/jovyan/.rsm-msba/jupyter"
        - name: NB_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['NB_UID']
        - name: NB_GID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['NB_GID']
        ports:
        - containerPort: 22
        volumeMounts:
        - name: home-volume
          mountPath: /home/jovyan
      volumes:
      - name: home-volume
        hostPath:
          path: /home/${USER}
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: rsm-msba-gpu-ssh-${USER}
  annotations:
    nodePort: "${NODE_PORT}"
spec:
  type: NodePort
  selector:
    app: rsm-msba-gpu
    user: ${USER}
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: ${NODE_PORT}  # Will be calculated and set by the startup script