services:
  selenium:
    image: selenium/standalone-firefox:latest
    platform: linux/amd64
    container_name: rsm-selenium
    environment:
      - SELENIUM_PORT=4444
    networks:
      - rsm-docker

networks:
  rsm-docker:
    name: rsm-docker
